### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by laxman07** [crazko/kalendario#15]
I think there are some recent changes in Google Calendar which make it stop working. Any suggestions?

**Comment by crazko** [comment]
Hey! That's partially true. This extension was built for old google calendar and I just haven't fully rewrite it for new one with material design. It should work locally, but the export for google play store is not working yet. Need some more time for that.

**Comment by crazko** [comment]
Took much more time then I expected... the extension is updated to work with new Google Calendar and can be installed from Chrome Store.
