### ISSUE TITLE
No Change in Calendar - Doesn't work.

### ISSUE THREAD

**Issue by waltgreenberg** [crazko/kalendario#52]
I had high hopes 8^(

Google Chrome
Google Chrome is up to date
Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by crazko** [comment]
Currently there's an error #50  when token is expired, try reload the page (or move between days if in Agenda view).

Could you provide some steps to reproduce?

**Comment by waltgreenberg** [comment]
I installed it and signed in with google is all.  No change at all.  Closed, reopened chrome, calendar, moved between pages, etc.  No effect from Kalendario.
![Kalendario](https://user-images.githubusercontent.com/5641016/75819091-ff08c180-5d67-11ea-95b0-e829453c8235.png)


![image](https://user-images.githubusercontent.com/5641016/75818713-62deba80-5d67-11ea-828f-acf0940a3a68.png)

![image](https://user-images.githubusercontent.com/5641016/75818583-214e0f80-5d67-11ea-85c8-10c46a36c3e0.png)

**Comment by crazko** [comment]
Would you be able to test a new version before release? I tried to make some fixes and works OK for me now. It'd be very helpful to me.

1. download and extract somewhere new version of extension [kalendario-test.zip](https://github.com/crazko/kalendario/files/4333991/kalendario-test.zip)
1. open the Extension Management page `chrome://extensions`
1. disable or remove Kalendario, if it's not already
1. enable **Developer mode**
1. **Load unpacked** extension, select directory from point 1.

Thanks!

**Comment by waltgreenberg** [comment]
Sorry, been busy. I'll have a look this wkend and get back to you.
