### ISSUE TITLE
HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by mikavaliviita** [crazko/kalendario#58]
Doesn't do anything.

This error shows up in Console:

`DevTools failed to load SourceMap: Could not load content for chrome-extension://ccoehijdbponhcemihobmdpaeenmgchg/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by crazko** [comment]
That warning shouldn't be a show stopper.

Can you provide more info? Like the browser you use, went the authentication process ok? And also, are you sure events have descriptions that should show up?

**Comment by mikavaliviita** [comment]
Chrome version if 84.0.4147.105

I think the authentication process went well. Is there a way to verify this?

I created events with description to test this.

**Comment by crazko** [comment]
I think it should be visible at https://myaccount.google.com/permissions, and look something like this:

![image](https://user-images.githubusercontent.com/1255989/89631777-86230e00-d8a1-11ea-87fc-44cecd431860.png)

You may also inspect extension via devtools from [chrome://extensions/](chrome://extensions/) address. Click **background page** and go to console/network tab. Try to list events in agenda, change days and observe if anything is sending in background.

![image](https://user-images.githubusercontent.com/1255989/89632210-2416d880-d8a2-11ea-8052-af36f2e2d8c4.png)

As of last resort, try to remove the extensions and add it again. I tried it with the same browser version now, works for me.

**Comment by mikavaliviita** [comment]
Access seems to be correct.

This is shown in Console:
```
Sending calendar list
Event '2020_BIRTHDAY_<removed>' doesn't have proper calendar 'addressbook#contacts@group.v.calendar.google.com'.
```
(removed id not shown...)

When disabling all other but my personal calendar, only **Sending calendar list** shows up.

**Comment by mikavaliviita** [comment]
Also tried reinstalling the extension, but that didn't help. It might have something to do with my set of calendars?

**Comment by mikavaliviita** [comment]
Is there any way I could debug this further?

**Comment by crazko** [comment]
The message `doesn't have proper calendar` should not lead to not fetching other events data.

When you disable all but your default calendar, having at least one event (at least created manually), it _should_ try to fetch data for it.

One thing that comes to my mind is that once data is fetched for some event, it does not fetch again because data is stored locally. Maybe try to refresh tab, but I can imagine you already tried...

---

Currently, there's no debug feature implemented besides those console logs which are visible in my screenshot above.

If anything comes to my mind, I'll get back to you.

**Comment by mikavaliviita** [comment]
So, this seems to be working with another account on the new MS Edge and Chrome. Just took some time to sync the details for all the events I guess (some of the events didn't show details at first). I think there is something causing this with my account.

**Comment by crazko** [comment]
Thanks for the info, that it's working. If you somehow find out, what causes the the error with your account, please, share it with me.
I think we can close this for now. We can re-open this issue in the future when we have more info.
